name: Codecov

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Floating Luogu
    steps:
    - uses: actions/checkout@v3

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: pnpm

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile

    - name: Run tests and collect coverage
      run: pnpm coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
